# Exports single-stroke (centerline) glyph paths from the Hershey vector fonts into ../glyphs.js.
# Neon tubes follow a centerline, so a stroke font gives real bendable tube paths (and a pen-order for the script draw-on).
# uv run --no-project --with Hershey-Fonts --index-url https://pypi.org/simple python tools/export_glyphs.py
import json, os
from HersheyFonts import HersheyFonts
out = {}
for key, fn, txt in [('good', 'scripts', 'Good Ideas'), ('served', 'futural', 'SERVED HERE'), ('open', 'futural', 'OPEN'), ('late', 'futural', 'LATE')]:
    f = HersheyFonts(); f.load_default_font(fn)
    res, prev = [], 0
    for i in range(len(txt)):                      # tag every stroke with the index of the character it belongs to
        ss = list(f.strokes_for_text(txt[:i + 1]))
        for s in ss[prev:]: res.append({'c': i, 'p': [[float(x), float(y)] for x, y in s]})
        prev = len(ss)
    out[key] = res
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'glyphs.js')
open(dst, 'w').write('// generated by tools/export_glyphs.py (Hershey fonts: scripts, futural). y is down.\nconst GLYPHS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
print('wrote', dst)
